#pragma once

#define WIFI_SSID "ssid"
#define WIFI_PASSWORD "password"

#define MAPQUESTAPIKEY ""
#define TIMEZONEAPIKEY ""
#define OPENWEATHERMAPAPIKEY ""
#define THINGSBOARDURL "http://thingsboard.domain.com"
#define THINGSBOARDAPIKEY ""
#define THINGSBOARDSOLARAPIKEY ""
#define THINGSBOARDB2BAPIKEY ""
#define THINGSBOARDMAINSAPIKEY ""
#define THINGSBOARDBATTERYAPIKEY ""

#define VICTRON_SOLAR_ADDRESS "11:22:33:44:55:66"
#define VICTRON_SOLAR_PASSCODE "123456"
#define VICTRON_B2B_ADDRESS "11:22:33:44:55:77"
#define VICTRON_B2B_PASSCODE "123456"
#define VICTRON_MAINS_ADDRESS "11:22:33:44:55:88"
#define VICTRON_MAINS_PASSCODE "123456"

#define KSENERGY_BATTERY_ADDRESS "11:22:33:44:55:99"